language: python
sudo: false
addons:
  firefox: "47.0.1"
  sauce_connect:
    username: "Your Sauce Labs username"
    access_key: "Your Sauce Labs access key"
python:
  - "2.7"
install:
  - pip install robotframework
  - pip install selenium
  - pip install decorator
  - pip install docutils
  -
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
env:
  matrix:
  - BROWSER=firefox
