language: python
sudo: required
python:
  - "2.7"
install:
  - pip install robotframework
  - pip install selenium
  - pip install decorator
  - pip install docutils
  -
before_script:
  - ./bin/install_browser.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
env:
  matrix:
  - BROWSER=phantomjs
  - BROWSER=firefox
  - BROWSER=chrome
