language: python
sudo: false
addons:
  firefox: "latest"
python:
  - "2.7"
install:
  - pip install robotframework
  - pip install selenium
  - pip install decorator
  - pip install docutils
  -
before_script:
  - "phantomjs --version"
  - "firefox --version"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "python test/run_tests.py python $BROWSER --noncritical known_issue_-_travisci"
env:
  matrix:
  - BROWSER=phantomjs
  - BROWSER=firefox
